language: ruby
sudo: false
cache: bundler

rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0

gemfile:
  - gemfiles/sidekiq_4.gemfile
  - gemfiles/sidekiq_5.gemfile

services:
  - redis-server

notifications:
  email: false
